/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wfsistemas.sysbank.apresentacao;

import br.com.wfsistemas.sysbank.apresentacao.ClassesUtil.CursorUtil;
import br.com.wfsistemas.sysbank.apresentacao.ClassesUtil.MensagemTela;
import br.com.wfsistemas.sysbank.excecao.ArgumentInvalidExeception;
import br.com.wfsistemas.sysbank.entidade.Usuario;
import br.com.wfsistemas.sysbank.negocio.UsuarioBO;
import java.awt.Cursor;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
/**
 *
 * @author wff
 */
public class TelaConsultaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaUsuarioForm
     */
    private TelaPrincipal telaPrincipal = null;
    List<Usuario> usuarios = new ArrayList<>();
    
    private CadastroUsuarioForm cadUsuarioForm;
    private TelaEditarDadosUsuario telaEditarDadosUsuario;

    public TelaConsultaUsuario() {
            prepararTela();
    }
    public void prepararTela(){
        try {
            this.initComponents();
            this.carregarDadosTabela();
            this.buscarTodosUsuario();
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Usuarios Cadastrados", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }
    public void buscarTodosUsuario() throws SQLException{           
        UsuarioBO usuarioBO = new UsuarioBO();
        usuarios = usuarioBO.buscarTodos();
        carregarDadosTabela();
    }
    public void carregarDadosTabela()throws SQLException{
        Model modelo  = new Model();
        tblUsuarios.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsultarUsuarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblConsultarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConsultarUsuarios.setText("Usuários do Sistema - SysBank");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsuarios);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/rubbish7 (2).png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(60, 30));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/pencil113.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setPreferredSize(new java.awt.Dimension(60, 30));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsultarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       this.excluirUsuario();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.editarUsuario();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaUsuario().setVisible(true);
            }
        });
    }
    private void exibirMensagemErro(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }

    private void exibirMensagemSucesso(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    private void editarUsuario(){
        int linhaSelecionada = tblUsuarios.getSelectedRow();
        if(linhaSelecionada != -1){
            Usuario usuarioSelecionado = usuarios.get(linhaSelecionada);
            
            TelaEditarDadosUsuario telaEditarDadosUsuario = new TelaEditarDadosUsuario(this, usuarioSelecionado);          
            
            if(this.telaEditarDadosUsuario != null){
                this.telaEditarDadosUsuario.dispose();
            }
            this.telaEditarDadosUsuario = new TelaEditarDadosUsuario(this, usuarioSelecionado);
            telaEditarDadosUsuario.setVisible(true);
            telaEditarDadosUsuario.toFront();            
            
        }else{
            String mensagem = "Nenhum aluno selecionado.";
                JOptionPane.showMessageDialog(this,mensagem,"Edição de aluno",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    public void excluirUsuario(){
        try {
            int linhaSelecionada = tblUsuarios.getSelectedRow();
            if (linhaSelecionada != -1) {
                Usuario usuarioSelecionado = usuarios.get(linhaSelecionada);

                int resposta;
                String mensagem = "Deseja excluir o usuario "
                        + usuarioSelecionado.getNome() + " (CPF: "
                        + usuarioSelecionado.getCpf() + ")?";
                String titulo = "Exclusão de usuario";
                resposta = JOptionPane.showConfirmDialog(this,
                        mensagem, titulo, JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_OPTION) {
                    UsuarioBO usuarioBO = new UsuarioBO();
                    usuarioBO.deletarUsuario(usuarioSelecionado);
                    this.buscarTodosUsuario();
                    this.carregarDadosTabela();
                    String mensagemSuceso = "Aluno "+
                            usuarioSelecionado.getNome()+
                            " (CPF: "
                            + usuarioSelecionado.getCpf() + ")"
                            + "excluído com sucesso.";
                    JOptionPane.showMessageDialog(this, 
                            mensagemSuceso, titulo, 
                            JOptionPane.INFORMATION_MESSAGE);
                    
                    
                }else{
                    exibirMensagemSucesso("Dados não excluidos", "Excluir usuário");
                }
            } else {
                String mensagem = "Nenhum usuario selecionado.";
                JOptionPane.showMessageDialog(this,
                        mensagem,
                        "Exclusão de usuario",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Exclusão de usuario", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultarUsuarios;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
public class Model extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return usuarios.size();
        }

        @Override
        public int getColumnCount() {
            return 6;
        }

        @Override
        public Object getValueAt(int linha, int coluna) {
            Usuario usuario = usuarios.get(linha);
            if(coluna == 0){
                return usuario.getCpf();
            }else if(coluna == 1){
                return usuario.getRg();
            }else if(coluna == 2){
               return usuario.getNome();
            }else if(coluna == 3){
                return usuario.getIdade();
            }else if(coluna == 4){
                return usuario.getCargo();
            }else{
                if(usuario.getPermissao() == 5){
                    return "Usuário Padrão";
                }else{
                    return "Usuário Administrador";
                }
            }
        }
        
        @Override
        public String getColumnName(int coluna){
            if(coluna == 0){
                return "CPF";
            }else if(coluna == 1){
                return "RG";
            }else if(coluna == 2){
               return "Nome"; 
            }else if(coluna == 3){
                return "Idade";
            }else if(coluna == 4){
                return "Cargo";
            }else{
                return "Permissão";
            }
        }
    
    }
}
