/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wfsistemas.sysbank.apresentacao;

import br.com.wfsistemas.sysbank.entidade.Agencia;
import br.com.wfsistemas.sysbank.negocio.AgenciaBO;
import br.com.wfsistemas.sysbank.apresentacao.TelaEditarDadosAgencia;
import br.com.wfsistemas.sysbank.apresentacao.ClassesUtil.CursorUtil;
import br.com.wfsistemas.sysbank.apresentacao.ClassesUtil.MensagemTela;
import br.com.wfsistemas.sysbank.apresentacao.TelaConsultaUsuario.Model;
import br.com.wfsistemas.sysbank.excecao.ArgumentInvalidExeception;
import java.awt.Cursor;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;


/**
 *
 * @author wff
 */
public class TelaConsultaAgencia extends javax.swing.JFrame {
    private TelaPrincipal telaPrincipal = null;
    private CadastroAgenciaForm cadastroAgenciaForm;
    private TelaEditarDadosAgencia telaEditarDadosAgencia;
    
    List<Agencia> agencias = new ArrayList<>();
    /**
     * Creates new form TelaConsultarAgencia
     */
    public TelaConsultaAgencia() {    
        prepararTela();
    }
    private void prepararTela(){
        try {
            this.initComponents();
            this.carregarDadosTabela();
            this.buscarTodasAgencias();
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Agencias Cadastrados", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }
    public void buscarTodasAgencias() throws SQLException{           
        AgenciaBO agenciaBO = new AgenciaBO();
        agencias = agenciaBO.buscarTodos();
        carregarDadosTabela();
    }
    private void carregarDadosTabela(){
        ModeloTabelaAgencia modelo  = new ModeloTabelaAgencia();
        tblResultado.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsultarUsuarios = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblConsultarUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConsultarUsuarios.setText("Agencias Cadastradas no Sistema - SysBank");

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/pencil113.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setPreferredSize(new java.awt.Dimension(60, 30));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/rubbish7 (2).png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setPreferredSize(new java.awt.Dimension(60, 30));
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblConsultarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsultarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        this.editarAgencia();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        this.excluirAgencia();
    }//GEN-LAST:event_btnExcluirActionPerformed
    private void editarAgencia(){
        int linhaSelecionada = tblResultado.getSelectedRow();
        if(linhaSelecionada != -1){
            Agencia agenciaSelecionado = agencias.get(linhaSelecionada);            
            TelaEditarDadosAgencia telaEditarDadosAgencia = new TelaEditarDadosAgencia(this, agenciaSelecionado);          
            
            if(this.telaEditarDadosAgencia != null){
                this.telaEditarDadosAgencia.dispose();
            }
            this.telaEditarDadosAgencia = new TelaEditarDadosAgencia(this, agenciaSelecionado);
            this.telaEditarDadosAgencia.setVisible(true);
            this.telaEditarDadosAgencia.toFront();            
            
        }else{
            String mensagem = "Nenhum aluno selecionado.";
                JOptionPane.showMessageDialog(this,mensagem,"Edição de aluno",JOptionPane.INFORMATION_MESSAGE);
        }
    }
    public void excluirAgencia(){
        try {
            int linhaSelecionada = tblResultado.getSelectedRow();
            if (linhaSelecionada != -1) {
                Agencia agenciaSelecionada = agencias.get(linhaSelecionada);

                int resposta;
                String mensagem = "Deseja excluir o agencia "
                        + agenciaSelecionada.getNome() + " (Numero Agencia: "
                        + agenciaSelecionada.getNumeroAgencia() + ")?";
                String titulo = "Exclusão de agencia";
                resposta = JOptionPane.showConfirmDialog(this,
                        mensagem, titulo, JOptionPane.YES_NO_OPTION);

                if (resposta == JOptionPane.YES_OPTION) {
                    AgenciaBO agenciaBO = new AgenciaBO();
                    agenciaBO.deletarAgencia(agenciaSelecionada);
                    this.buscarTodasAgencias();
                    this.carregarDadosTabela();
                    String mensagemSuceso = "Agencia "+
                            agenciaSelecionada.getNome()+
                            " Numero Agencia: "
                            + agenciaSelecionada.getNumeroAgencia() + ")"
                            + "excluído com sucesso.";
                    JOptionPane.showMessageDialog(this, 
                            mensagemSuceso, titulo, 
                            JOptionPane.INFORMATION_MESSAGE);
                    
                    
                }else{
                    exibirMensagemSucesso("Dados não excluidos", "Excluir usuário");
                }
            } else {
                String mensagem = "Nenhum cliente selecionado.";
                JOptionPane.showMessageDialog(this,
                        mensagem,
                        "Exclusão de cliente",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            String mensagem = "Erro inesperado! Informe a mensagem de erro ao administrador do sistema.";
            mensagem += "\nMensagem de erro:\n" + e.getMessage();
            JOptionPane.showMessageDialog(this, mensagem, "Exclusão de cliente", JOptionPane.ERROR_MESSAGE);
            this.dispose();
        }
    }
    private void exibirMensagemErro(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.ERROR_MESSAGE);
    }

    private void exibirMensagemSucesso(String mensagem, String titulo) {
        JOptionPane.showMessageDialog(this, mensagem, titulo, JOptionPane.INFORMATION_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultaAgencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultaAgencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultarUsuarios;
    private javax.swing.JTable tblResultado;
    // End of variables declaration//GEN-END:variables
    private class ModeloTabelaAgencia extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return agencias.size();
        }

        @Override
        public int getColumnCount() {
            return 7;
        }

        @Override
        public Object getValueAt(int linha, int coluna) {
            Agencia agencia  = agencias.get(linha);
            if(coluna == 0){
                return agencia.getNome();
            }
            else if(coluna == 1){
                return agencia.getEndereco();
            }else if(coluna == 2){
                return agencia.getCidade();
            }
            else if(coluna == 3){
               return agencia.getEstado();
            }else if(coluna == 4){
                 return agencia.getTelefone();
            }else if(coluna == 5){
                return agencia.getNumeroAgencia();
            } else{
                if(agencia.getPermissao() == 5){
                    return "Usuário Padrão";
                }else{
                    return "Usuário Administrador";
                }
            }
        }
        
        @Override
        public String getColumnName(int coluna){
            if(coluna == 0){
                return "Numero da Agencia:";
            }else if(coluna == 1){
                return "Endereco:";
            }else if(coluna == 2){
                return "Cidade";
            }else if(coluna == 3){
               return "Estado"; 
            }else if(coluna == 4){
                return "Numero da Agencia";
            }else if(coluna == 5){
                return "Telefone";
            }else{
                return "Permissao";
            }
        }
    }
}
