/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wfsistemas.sysbank.apresentacao;

import br.com.wfsistemas.sysbank.apresentacao.ClassesUtil.CursorUtil;
import br.com.wfsistemas.sysbank.apresentacao.ClassesUtil.MensagemTela;
import br.com.wfsistemas.sysbank.entidade.Cliente;
import br.com.wfsistemas.sysbank.excecao.ArgumentInvalidExeception;
import br.com.wfsistemas.sysbank.entidade.Usuario;
import br.com.wfsistemas.sysbank.negocio.ClienteBO;
import br.com.wfsistemas.sysbank.negocio.UsuarioBO;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author wff
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private CadastroClienteForm cadastroClienteForm ;
    private CadastroUsuarioForm cadastroUsuarioForm ;
    private TelaAlterarSenha telaAlterarSenha = null;
    private Usuario usuario = null;
    private Cliente cliente = null;
    private TelaConsultaUsuario telaConsultaUsuario = null;
    private TelaConsultaCliente telaConsultaCliente = null;
    private TelaConsultaAgencia telaConsultaAgencia = null;
    private TelaConsultaConta telaConsultaConta = null;
    private CadastroContaForm cadastroContaForm = null;
    private CadastroAgenciaForm cadastroAgenciaForm = null;
    private TelaSaqueConta telaSaqueConta = null;
    private TelaDepositoConta telaDepositoConta = null;
    //private List<Usuario> usuarios = null;
    /**
     * Creates new form InicioBanckForm
     */
    public TelaPrincipal(Usuario usuario) {
        initComponents();
        Color suacor = new Color(60, 59, 55);
        this.barraMenuPrincipal.setBackground(suacor);
        this.usuario = usuario;
        this.mnuUsuarioAtivo1.setText(usuario.getNome());
        this.carregarUsuarioPermissao();
        //this.Agencia = usuario.getAgencia;
    }

    private TelaPrincipal() {
        initComponents();
    }
    private void carregarUsuarioPermissao(){
        if(usuario.getPermissao() == 5){
            itemAgencias.setVisible(false);
            itemUsuarios.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFundo = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        itemContas = new javax.swing.JMenuItem();
        spdCadastros = new javax.swing.JPopupMenu.Separator();
        itemUsuarios = new javax.swing.JMenuItem();
        itemAgencias = new javax.swing.JMenuItem();
        mnuContas = new javax.swing.JMenu();
        itemSaques = new javax.swing.JMenuItem();
        itemDepositos = new javax.swing.JMenuItem();
        spdContas = new javax.swing.JPopupMenu.Separator();
        itemSados = new javax.swing.JMenuItem();
        itemTransferencia = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        itemConsultarClientes = new javax.swing.JMenuItem();
        itemConsultarContas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ItemConsultarUsuarios = new javax.swing.JMenuItem();
        ItemConsultarAgencias = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        itemGrafico = new javax.swing.JMenuItem();
        itemRelatorioClientes = new javax.swing.JMenuItem();
        itemRelatorioConta = new javax.swing.JMenuItem();
        mnuAjuda = new javax.swing.JMenu();
        mnuUsuarioAtivo1 = new javax.swing.JMenu();
        btnAlterarSenha = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        lblFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/moneybox (3)_1.png"))); // NOI18N
        lblFundo.setAlignmentX(0.5F);

        barraMenuPrincipal.setMaximumSize(new java.awt.Dimension(510, 32769));
        barraMenuPrincipal.setPreferredSize(new java.awt.Dimension(359, 35));

        mnuCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/application_form_add.png"))); // NOI18N
        mnuCadastros.setText("Cadastro");

        itemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        itemClientes.setText("Clientes");
        itemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(itemClientes);

        itemContas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        itemContas.setText("Contas");
        itemContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemContasActionPerformed(evt);
            }
        });
        mnuCadastros.add(itemContas);
        mnuCadastros.add(spdCadastros);

        itemUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        itemUsuarios.setText("Usuarios");
        itemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuariosActionPerformed(evt);
            }
        });
        mnuCadastros.add(itemUsuarios);

        itemAgencias.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        itemAgencias.setText("Agencias ");
        itemAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgenciasActionPerformed(evt);
            }
        });
        mnuCadastros.add(itemAgencias);

        barraMenuPrincipal.add(mnuCadastros);

        mnuContas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/money.png"))); // NOI18N
        mnuContas.setText("Operações Conta");

        itemSaques.setText("Saques");
        itemSaques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaquesActionPerformed(evt);
            }
        });
        mnuContas.add(itemSaques);

        itemDepositos.setText("Depositos");
        itemDepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDepositosActionPerformed(evt);
            }
        });
        mnuContas.add(itemDepositos);
        mnuContas.add(spdContas);

        itemSados.setText("Saldos");
        mnuContas.add(itemSados);

        itemTransferencia.setText("Transfências");
        mnuContas.add(itemTransferencia);

        barraMenuPrincipal.add(mnuContas);

        mnuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/zoom.png"))); // NOI18N
        mnuConsultas.setText("Consultas");

        itemConsultarClientes.setText("Clientes");
        itemConsultarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarClientesActionPerformed(evt);
            }
        });
        mnuConsultas.add(itemConsultarClientes);

        itemConsultarContas.setText("Contas");
        itemConsultarContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarContasActionPerformed(evt);
            }
        });
        mnuConsultas.add(itemConsultarContas);
        mnuConsultas.add(jSeparator2);

        ItemConsultarUsuarios.setText("Usuarios");
        ItemConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemConsultarUsuariosActionPerformed(evt);
            }
        });
        mnuConsultas.add(ItemConsultarUsuarios);

        ItemConsultarAgencias.setText("Agencias");
        ItemConsultarAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemConsultarAgenciasActionPerformed(evt);
            }
        });
        mnuConsultas.add(ItemConsultarAgencias);

        barraMenuPrincipal.add(mnuConsultas);

        mnuRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/page_white_acrobat.png"))); // NOI18N
        mnuRelatorios.setText("Relatórios");

        itemGrafico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        itemGrafico.setText("Grafico");
        mnuRelatorios.add(itemGrafico);

        itemRelatorioClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        itemRelatorioClientes.setText("Relatorio de Clientes");
        itemRelatorioClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRelatorioClientesActionPerformed(evt);
            }
        });
        mnuRelatorios.add(itemRelatorioClientes);

        itemRelatorioConta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        itemRelatorioConta.setText("Relatorio de Contas");
        mnuRelatorios.add(itemRelatorioConta);

        barraMenuPrincipal.add(mnuRelatorios);

        mnuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/help.png"))); // NOI18N
        mnuAjuda.setText("Ajuda");
        barraMenuPrincipal.add(mnuAjuda);

        mnuUsuarioAtivo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/status_online.png"))); // NOI18N

        btnAlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/key.png"))); // NOI18N
        btnAlterarSenha.setText("Alterar senha");
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });
        mnuUsuarioAtivo1.add(btnAlterarSenha);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wfsistemas/sysbank/apresentacao/icones/status_busy.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        mnuUsuarioAtivo1.add(btnSair);

        barraMenuPrincipal.add(mnuUsuarioAtivo1);

        setJMenuBar(barraMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(lblFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addGap(334, 334, 334))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(lblFundo, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(112, 112, 112))
        );

        setBounds(0, 0, 818, 557);
    }// </editor-fold>//GEN-END:initComponents

    private void itemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuariosActionPerformed
        if (this.cadastroUsuarioForm == null) {
            try {                            
                this.cadastroUsuarioForm = new CadastroUsuarioForm();
            } catch (SQLException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
        cadastroUsuarioForm.setVisible(true);
        
    }//GEN-LAST:event_itemUsuariosActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClientesActionPerformed
        if (this.cadastroClienteForm == null) {
                this.cadastroClienteForm = new CadastroClienteForm();                            
        }
          
        cadastroClienteForm.setVisible(true);
        
    }//GEN-LAST:event_itemClientesActionPerformed

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        // TODO add your handling code here:
        if (this.telaAlterarSenha == null) {
                this.telaAlterarSenha = new TelaAlterarSenha(this.usuario);
        } 
        telaAlterarSenha.setVisible(true);

    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:

        int resposta;
        String mensagem = "Deseja sair do sistema ?";
        String titulo = "Sair";
        resposta = JOptionPane.showConfirmDialog(null, mensagem, titulo, JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            TelaLogin telaLogin = new TelaLogin();
            telaLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void ItemConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemConsultarUsuariosActionPerformed
      // TODO add your handling code here:
        if (this.telaConsultaUsuario == null ) {

                this.telaConsultaUsuario = new TelaConsultaUsuario();
                
        }
        telaConsultaUsuario.setVisible(true);
        telaConsultaUsuario.toFront();      
    }//GEN-LAST:event_ItemConsultarUsuariosActionPerformed

    private void itemConsultarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarClientesActionPerformed
    if (this.telaConsultaCliente == null ) {

                this.telaConsultaCliente = new TelaConsultaCliente();
                
        }
        telaConsultaCliente.setVisible(true);
        telaConsultaCliente.toFront();      

    }//GEN-LAST:event_itemConsultarClientesActionPerformed

    private void itemAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgenciasActionPerformed
        if(this.cadastroAgenciaForm == null) {
            this.cadastroAgenciaForm = new CadastroAgenciaForm();
        }
        cadastroAgenciaForm.setVisible(true);
        cadastroAgenciaForm.toFront();
    }//GEN-LAST:event_itemAgenciasActionPerformed

    private void itemContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemContasActionPerformed
        if (this.cadastroContaForm == null ) {

            this.cadastroContaForm = new CadastroContaForm(usuario);
                
        }
        cadastroContaForm.setVisible(true);
        cadastroContaForm.toFront();      
    }//GEN-LAST:event_itemContasActionPerformed

    private void ItemConsultarAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemConsultarAgenciasActionPerformed
       if(this.telaConsultaAgencia == null){
           this.telaConsultaAgencia = new TelaConsultaAgencia();
       }
       telaConsultaAgencia.setVisible(true);
       telaConsultaAgencia.toFront();
    }//GEN-LAST:event_ItemConsultarAgenciasActionPerformed

    private void itemRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatorioClientesActionPerformed
        if (this.telaConsultaCliente == null ) {

                this.telaConsultaCliente = new TelaConsultaCliente();
                
        }
        telaConsultaCliente.gerarRelatorio(); 
    }//GEN-LAST:event_itemRelatorioClientesActionPerformed

    private void itemSaquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaquesActionPerformed
        if (this.telaSaqueConta == null ) {

                this.telaSaqueConta = new TelaSaqueConta();
                
        }
        this.telaSaqueConta.setVisible(true);
        this.telaSaqueConta.toFront();
    }//GEN-LAST:event_itemSaquesActionPerformed

    private void itemDepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDepositosActionPerformed
        if (this.telaDepositoConta == null ) {

                this.telaDepositoConta = new TelaDepositoConta();
                
        }
        this.telaDepositoConta.setVisible(true);
        this.telaDepositoConta.toFront();
    }//GEN-LAST:event_itemDepositosActionPerformed

    private void itemConsultarContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarContasActionPerformed
     if (this.telaConsultaConta == null ) {

                this.telaConsultaConta = new TelaConsultaConta();
                
        }
        this.telaConsultaConta.setVisible(true);
        this.telaConsultaConta.toFront();
    }//GEN-LAST:event_itemConsultarContasActionPerformed

    public static void main(String[] args) {
        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
            try {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                System.err.println("Erro no Tema da Aplicação");
            }
        }
        TelaPrincipal telaPrincipal= new TelaPrincipal();
        telaPrincipal.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemConsultarAgencias;
    private javax.swing.JMenuItem ItemConsultarUsuarios;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JMenuItem btnAlterarSenha;
    private javax.swing.JMenuItem btnSair;
    private javax.swing.JMenuItem itemAgencias;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenuItem itemConsultarClientes;
    private javax.swing.JMenuItem itemConsultarContas;
    private javax.swing.JMenuItem itemContas;
    private javax.swing.JMenuItem itemDepositos;
    private javax.swing.JMenuItem itemGrafico;
    private javax.swing.JMenuItem itemRelatorioClientes;
    private javax.swing.JMenuItem itemRelatorioConta;
    private javax.swing.JMenuItem itemSados;
    private javax.swing.JMenuItem itemSaques;
    private javax.swing.JMenuItem itemTransferencia;
    private javax.swing.JMenuItem itemUsuarios;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JMenu mnuAjuda;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenu mnuContas;
    private javax.swing.JMenu mnuRelatorios;
    private javax.swing.JMenu mnuUsuarioAtivo1;
    private javax.swing.JPopupMenu.Separator spdCadastros;
    private javax.swing.JPopupMenu.Separator spdContas;
    // End of variables declaration//GEN-END:variables
}
